language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

before_script:
    - composer install -o --no-ansi --no-suggest
    - composer update -o --no-ansi --no-suggest

script:
    - vendor/bin/phpcs src -p --extensions=php --standard=ruleset.xml
    - vendor/bin/phpstan analyse src -c ruleset.neon -l 7

notifications:
    email: false