language: php

php:
    - 7.4

before_script:
    - composer install -o --no-ansi --no-suggest

script:
    - vendor/bin/phpcs src --standard=ruleset.xml
    - vendor/bin/phpstan analyse src -c ruleset.neon -l 8 --error-format custom

notifications:
    email: false